name: project_flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  curved_navigation_bar: ^1.0.6
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.9.1
  intl: ^0.19.0
  percent_indicator: ^4.2.5
  pie_chart: ^5.4.0
  pie_chart_sz: ^1.1.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login/
    - assets/onBording/
    - assets/users/
    - assets/home/
    - assets/project/
    - assets/
    - assets/translations/